# See Tutorial.mk for more details on the build process

#For the 32bit libs lookup glew localy, for the 64 ones use the system libs
LINK_LIBS_32 = -lglut -L ./glew -lGLEW -lGL -lGLU
LINK_LIBS_64 = -lglut -lGLEW -lGL -lGLU

TUTORIALS_DIR = ../..
TARGET_NAME = s3tc
include ../../Tutorial.mk
