#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

#include "../../common/service.h"

class CAffect
{
	public:
		DWORD dwType;
		BYTE bApplyOn;
		long lApplyValue;
		DWORD dwFlag;
		long lDuration;
		long lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,
	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX, // 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,
	AFFECT_POISON,
	AFFECT_STUN, // 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,
	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE, // 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,
	AFFECT_POLYMORPH, // 220
	AFFECT_MOUNT,
	AFFECT_WAR_FLAG, // 222
	AFFECT_BLOCK_CHAT, // 223
	AFFECT_CHINA_FIREWORK,
	AFFECT_BOW_DISTANCE, // 225
	AFFECT_DEF_GRADE, // 226
	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502, // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT = 503, // PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND = 504, // PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST = 505,
	AFFECT_GOLD_BONUS = 506,
	AFFECT_PREMIUM_END = 509,//whats teh affect id

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_NO_BOOK_DELAY = 513,
	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,
	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,
	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,
	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

#ifdef ENABLE_GROWTH_PET_SYSTEM
	AFFECT_GROWTH_PET = 544,
#endif

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,
	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

#ifdef ENABLE_RENEWAL_AFFECT
	AFFECT_BLEND = 548,
	AFFECT_MALL_PLUS = 549,
	AFFECT_BLEND_PLUS = 550,
#endif

#ifdef ENABLE_PET_SYSTEM
	AFFECT_PET_SUMMON = 564,
#endif

#ifdef ENABLE_RENEWAL_OFFLINESHOP
	AFFECT_DECORATION = 703,
#endif

#ifdef ENABLE_MULTI_FARM_BLOCK
	AFFECT_MULTI_FARM_PREMIUM = 704,
#endif

#ifdef ENABLE_RENEWAL_PREMIUM_SYSTEM
	AFFECT_PREMIUM_ACCOUNT = 705,
#endif

#ifdef ENABLE_AUTOMATIC_PICK_UP_SYSTEM
	AFFECT_AUTO_PICK_UP = 706,
#endif

#ifdef ENABLE_BIOLOG_SYSTEM
	AFFECT_BIOLOG = 800,
#endif

#ifdef __AUTO_HUNT__
	AFFECT_AUTO_HUNT =830,
	AFFECT_AUTO_HUNT_AFFECT =831,
#endif

	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,						// 0	- Binary
	AFF_YMIR,						// 1	- 0
	AFF_INVISIBILITY,				// 2	- 1
	AFF_SPAWN,						// 3	- 2
	AFF_POISON,						// 4	- 3
	AFF_SLOW,						// 5	- 4
	AFF_STUN,						// 6	- 5
	AFF_DUNGEON_READY,				// 7	- 6
	AFF_DUNGEON_UNIQUE,				// 8	- 7
	AFF_BUILDING_CONSTRUCTION_SMALL,// 9	- 8
	AFF_BUILDING_CONSTRUCTION_LARGE,// 10	- 9
	AFF_BUILDING_UPGRADE,			// 11	- 10
	AFF_MOV_SPEED_POTION,			// 12	- 11
	AFF_ATT_SPEED_POTION,			// 13	- 12
	AFF_FISH_MIND,					// 14	- 13
	AFF_JEONGWIHON,					// 15	- 14
	AFF_GEOMGYEONG,					// 16	- 15
	AFF_CHEONGEUN,					// 17	- 16
	AFF_GYEONGGONG,					// 18	- 17
	AFF_EUNHYUNG,					// 19	- 18
	AFF_GWIGUM,						// 20	- 19
	AFF_TERROR,						// 21	- 20
	AFF_JUMAGAP,					// 22	- 21
	AFF_HOSIN,						// 23	- 22
	AFF_BOHO,						// 24	- 23
	AFF_KWAESOK,					// 25	- 24
	AFF_MANASHIELD,					// 26	- 25
	AFF_MUYEONG,					// 27	- 26
	AFF_REVIVE_INVISIBLE,			// 28	- 27
	AFF_FIRE,						// 29	- 28
	AFF_GICHEON,					// 30	- 29
	AFF_JEUNGRYEOK,					// 31	- 30
	AFF_TANHWAN_DASH,				// 32	- 31
	AFF_PABEOP,						// 33	- 32
	AFF_CHEONGEUN_WITH_FALL,		// 34	- 33
	AFF_POLYMORPH,					// 35	- 34
	AFF_WAR_FLAG1,					// 36	- 35
	AFF_WAR_FLAG2,					// 37	- 36
	AFF_WAR_FLAG3,					// 38	- 37
	AFF_CHINA_FIREWORK,				// 39	- 38
	AFF_HAIR,						// 40	- 39
	AFF_GERMANY,					// 41	- 40
	AFF_DS,							// 42	- 41
#ifdef ENABLE_RENEWAL_TEAM_AFFECT
	AFF_TEAM_SA,					// 43	- 42
	AFF_TEAM_GA,					// 44	- 43
	AFF_TEAM_GM,					// 45	- 44
	AFF_TEAM_TGM,					// 45	- 46
#endif
#ifdef ENABLE_RENEWAL_PREMIUM_SYSTEM
	AFF_PREMIUM,					// 46	- 47
#endif
#ifdef __AUTO_HUNT__
	AFF_AUTO_HUNT,					// 47	- 48
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect sonsuz olacaðý zaman kullan.
	// Sürekli zaman azalttýðý için sonsuzluðu çok büyük bir deðerle taklit et.
	//// 24 bit küçük kaldýðý için 25 bit kullanýlýr.
	// ... 25 bit dendiði halde yorum satýrlarýnda 29 bit kullanýldýðý söyleniyor...
	// Collect quest’te sonsuz süreyi 60 yýl olarak kullandýðýmýzdan, burada da 60 yýl yapalým.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
